<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\engine_common\EngineCommon.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ServerGarbageCollection>false</ServerGarbageCollection>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\Custom\Engine\Jobs\BlmDefinition.cs" Link="Jobs\BlmDefinition.cs" />
    <Compile Include="..\..\Custom\Engine\Jobs\NinDefinition.cs" Link="Jobs\NinDefinition.cs" />
  </ItemGroup>
</Project>
